config/routes.rb
Rails.application.routes.draw do
  resources :entries
  root to: "entries#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:name, :age, :gender, :des)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name,class:"h6"%>
    <%= form.text_field :name,class:"form-control"%>
  </div>

  <div class="field">
    <%= form.label :age,class:"h6" %>
    <%= form.number_field :age,class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :gender,class:"h6" %>
    <%= form.text_field :gender,class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :designation,class:"h6" %>
    <%= form.text_field :des,class:"form-control" %>
  </div>
<div class="text-center">
  <div class="btn btn-warning">
    <%= form.submit  %>
  </div>
</div>
  <% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<div class="text-center mt-4">
<%= link_to 'Show', @entry ,class:"btn btn-primary text-white" %> 
<%= link_to 'Back', entries_path ,class:"btn btn-success text-white"%>
</div>

app/views/entries/index.html.erb
<div>
<div class="text-center">
<%= link_to 'New Entry', new_entry_path, class:"btn btn-outline-primary text-info" %>

</div>

 <% v=0%>
 <div class="mt-5">
   <% @entries.each do |entry| %>
     <%v+=1%>
     <div class="row mb-3">
     <div class="col sm">
     <div class="card shadow">
     
     <div class="card-body">
     <div class="container">
     <div class="row">
       <div class="col-6">
       <p><%=v%></p>
       <h5 class="card-title"><b>Name: </b><%= entry.name %></h5>
       <h5 class="card-title"><b>Age: </b><%= entry.age %></h5>
       </div>
       <div class="col-6">
       <p></p>

       <p class="card-text"><b>Gender: </b><%= entry.gender %></p>
       <p class="card-text"><b>Designation: </b><%= entry.des %></p>
       </div>
     </div>
     </div>
       


       <div class="row text-center">
       <div class="col-4">
       <div>
       <%= link_to 'Show', entry, class:"btn btn-info text-white" %>
       </div>
       </div>
       <div class="col-4">
       <div>
       <%= link_to 'Edit', edit_entry_path(entry), class:"btn btn-warning text-white" %>
       </div>
       </div>
       <div class="col-4">
       <div>
       <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger text-white" %>
       </div>
       </div>
       </div>
      
     </div>

     </div>
     </div>
     </div>
     
   <% end %>
 </div>
</div>

app/views/entries/new.html.erb
<%= render 'form', entry: @entry %>

<div class="text-center mt-4">
<%= link_to 'Back', entries_path,class:"btn btn-danger rounded text-white" %>
</div>  

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>
<div class="mt-5">
<div class ="card shadow">
 <div class="pl-4 pt-2 pb-3">
<div class="h9">
<p>
  <strong>Name:</strong>
  <%= @entry.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @entry.age %>
</p>


<p>
  <strong>Gender:</strong>
  <%= @entry.gender %>
</p>

<p>
  <strong>Des:</strong>
  <%= @entry.des %>
</p>
</div>
<div class="text=left">
<%= link_to 'Edit', edit_entry_path(@entry) ,class:"btn btn-info rounded text-white"%> 
<%= link_to 'Back', entries_path ,class:"btn btn-danger rounded text-white" %>
</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  <%= render "shared/header" %>
  <div class="container mt-5">
  <%= yield %>

  </div>
<% if notice.present?  %>
<div class="alert alert-primary" role="alert">
<%=notice%>
</div>
<% end %>  
<% if notice.present?  %>
<div class="alert alert-warning" role="alert">
<%=alert%>
</div>
<% end %> 
  </body>
</html>

app/views/shared/_header.html.erb
<div class="text-white text-center">
<div class="bg-primary jumbotron jumbotron-fluid rounded">
  <div class="container">
    <h1 class="display-4">Employer App</h1>
    <p class="lead mt-3">Manage Employer CREATE.READ.EDIT.DELETE</p>
  </div>
</div>
</div>